> Prediction is very difficult, especially if it's about the future. - Niels Boh

# Introduction
Selecting and implementing the “right” machine learning algorithm to predict the future based upon past data is a necessary, but not sufficient, condition for success as a data scientist. Data science and the outcomes it produces may be complex and difficult to explain.  Yet, the effective data scientist must be equally facile at explaining her approach and findings to both colleagues and non-technical stakeholders.

In this ___ part series, we examine and contrast the most widely used machine learning classification algorithms.  Unlike regression algorithms which predict continuous outcomes, classifiers assign unseen observations to one or more classes, based upon insights, historical relationships and trends in the labeled training data.

## What will you learn?
By the end of this series, you will be able to:   
1.	Describe the most important machine learning classifiers   
2.	Relate their strengths, weaknesses and underlying assumptions   
3.	Identify the problems for which the algorithms are best suited   
4.	Implement the classifiers in Python   
5.	Evaluate and contrast the performance of the algorithms   

## How will we get there?   
We will take a case-based approach as follows:  

1. Case Introduction   
2. Exploratory Data Analysis   
3. Machine Learning and Classification Review   
    3.1. Machine Learning Tasks   
    3.2. Machine Learning Applications      
    3.3. Linear Algebra Review   
    3.4. The Classification Problem   
4. Linear Classifiers   
    4.1. Logistic Regression   
    4.2. Linear Discriminant Analysis   
    4.3. Support Vector Machines   
5. Non-Linear Classifiers    
    5.1. K-Nearest Neighbors   
    5.2. Generalized Additive Models for Classification  
    5.3. Neural Networks   
6. Tree-Based Classifiers    
    6.1. Classification Tree   
    6.2. Bagging    
    6.3. Random Forests   
    6.4. Boosting   
7. Discussion  
8. Conclusions  
