# What IS Machine Learning: A Review
Arthur Samuel, a pioneer in computer gaming and artificial intelligence at IBM, first coined the term "Machine Learning" in 1959. It was first defined as:

> "Field of study that gives computers the ability to learn without being explicitly programmed."

Tom M. Mitchell, a professor at Carnegie Mellon University, later provided a more formal definition of the algorithms studied in the machine learning field: 

>"A computer program is said to learn from experience E with respect to some class of tasks T and performance measure P if its performance at tasks in T, as measured by P, improves with experience E."

In case these definitions are a bit too abstract for your tastes, consider what a machine learning algorithm must do. 

## Machine Learning Tasks
Machine learning tasks are typically classified into two broad categories: supervised learning and unsupervised learning.  

* Supervised learning is extant when the computer is presented with examples or training data with both the predictors or inputs and the output.  The objective is to learn a general rule that maps inputs to outputs. 

* Unsupervised learning occurs when no output labels are given to the learning algorithm.  The learning objective is to find structure in the data.

So, to which applications do we apply supervising and unsupervised learning tasks?

## Machine Learning Applications
Machine learning can be also categorized in terms of its applications, including:

* Classification:  A supervised learning technique whereby the training data is divided into two or more classes. The algorithm must produce a model that assigns unseen observations to one (or more) of these classes.  

*	Regression: Another supervised learning task that models the relationship between a continuous dependent variable and one or more independent variables (or ‘predictors’).  

* Clustering: This unsupervised learning task divides observations into groups based upon the structure of and relationships among the predictors.  Unlike classification, the groups are not known beforehand. 

Bringing it down to earth, the essential task for a machine learning algorithm is to generalize its experience. Generalize, in the context of our case, is the ability to predict a decision accurately on new, unseen data. Since our case involves a discrete binary response, we will be exploring, modeling and evaluating supervised machine learning algorithms called *classifiers*. 

A solid foundation in linear algebra is requisite for a deeper understanding of, and intuition into machine learning algorithms. Next we review the linear algebra concepts constitutive to machine learning.
