RAW_DATA_DIR = "../../data/raw"
INTERIM_DATA_DIR = "../../data/interim"
PROCESSED_DATA_DIR = "../../data/processed"
EXTERNAL_DATA_DIR = "../../data/external"
ANALYSIS_DIR = "C:\\Users\\John\\Documents\\Data Science\\Libraries\\AnalyzePython"
DOCUMENTS_DIR = "../docs"
UTILITIES_DIR = "C:\\Users\\John\\Documents\\Data Science\\Libraries\\Utilities"
