RAW_DATA_DIR = "../data/raw"
INTERIM_DATA_DIR = "../data/interim"
PROCESSED_DATA_DIR = "../data/processed"
EXTERNAL_DATA_DIR = "../data/external"
ANALYSIS_PATH = "C:\\Users\\John\\Documents\\Data Science\\Libraries\\AnalyzePython"
